---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invidious
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: invidious-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INVIDIOUS_HMAC_KEY: "{{ .invidious_hmac_key }}"
  dataFrom:
    - extract:
        key: invidious
      rewrite:
        - regexp:
            source: "(.*)"
            target: "invidious_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invidious-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: invidious-db-secret
    template:
      type: Opaque
      data:
        INVIDIOUS_DATABASE_URL: '{{ index . "uri" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-invidious
