# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:1CaFVztovQFQP4EAOY4u8/ccT/HSsnakvO4A97B9DCOgBHzqqjbQ/gDunxKzNyeglbaO800LuZZmuqKuoIlP3jRU6zelVDTi8rYPz5FfGZYzaZJxb2uB/m9SMhoVnuermYiBdqB1RPeWEa6VNSyiHLeYqxvKRhYqQ/N9teE0A8SKThBzD2RgC9tlIJ2cjelOW5ce8bGqQbo8jlZ9ic+3Mn3cC47lngidKp+PQdm8Yjz9E1+tYDRubTulLQLXha3eo9Kr3wRdChur6S/VGtDtb7DfFpmFeLs3XlGQ3iKM/IzMw7v/g5vRrvw1HfVL0LLP4KHvliK3rN+wvsVbT049AwAF3ZyuDlkHNMAkbcb3QNl8hsJuehL0X/wfF5GZyhxHX9lEI6u1eqKei3QfoRznKz/RC+kXhD38kClgOcgLBZyJJEfYqls3o0Oxk+llk3IVI5KalPWw9Usi0iWxY4tAB9JyLuglRt3DkfDHsmsQXrZYwRlo+RZ/azFY26pzD5nLGw7l8K7y3Da7JBSDzgB+dTKOgNg5BQatTJMSu7osC3UnbfImby03UPG9PS8Oh5GQtfkGLl581iGF17hYtn2yv5hPXTRIiXEJXtd0o8ofWOi7BpvtpUz14fcbUDwJhnITf7O9iNrkGfPXMdCZdVyGWq4iM4fAQ7XrtbzbfAlDFnmtAcn+yQmjWuXtyvNCjDFdvs9VF+lg9jfR7W1d1VOnnsgb9GZ+vMlbgZlq02RHj8QEVf1Purqfcdkjzbmi2Cy2ro5elVJqoUGkcqKE9nEmnyHxlZJw6sfIfjmsfJbGrzAVFiy5PISbeQVuqE42J77KyBRL31LwRrkYW75foHtYUeqCjHAB0J+B9Nymp88igzgWCC8l3C4fcidfVV/3DiBEigSCwrEH3+K/hlAfSvdyNZQ2sPS18+B0FtQr+8mIrychTvCOkmSQhO6GNC50gCryTuzDkygdPILSRLue2O2tN7v5P1oR3itmzdctDzVqz5R7ScbRtx/BS7Q7B3VIxmmXhfayGzCdAqmuz5XHo6al0W32EtKUGeNPJzRlGqEgEaJRoNi66Gq0RrPiaqG5uI67nJwDmIbFALEJEtgOl+HOf6ZDT666bRwmcOuUgwJYDENlJAueSoBtywHPwrsbJntP7BxwD1Gj10iQ7gZIn5GbAFG4wR1RlpAsA9fjChJun8L9Uron+uFAWkSXsuHH/uwwyOpCWa9viGMBLsMsLXcNtKY4nHp5Tu1+RM2U69KRgFQ6fE98ttX7z9e5MwYCadRMjAbtPDl6kW5VzSCj9K5EZvO21xKSE5bhewBu5Q7Fzq3REFS+r5kxaH1cSn5wDwrlinLGelxUt41MVDHz8bqiufubsdlhWNrEEFXl+MOJycNIlhgOB3ONIBdqq6+z64fsENG+/TD8ZKQ/tUt54vdDcynmXWKHcSoHzR7yKJ7mIZdSpU3Gtyq3d8xycgNC3Bk9GHiCAxXJ0NgYqGlOSCciREKUfhkzex1e4uZVE1UlMcoNXMvXVCr+iOKlPY3M0NHkRQTJmj1Wo95vXMXkzizkDLgT7CPxwlbskTG2mtK6CVUdcxwaKsmv5bBiRH33St6Ao/IiH8MFXrBqYTukvzcARERT0f1AHlsqUPpI8kTJ/WpSWrd+10lDRvt1aNyxw6MDiX75jeS7Lmf4Zdu/yYRXiVWWX+9uoW3aAljCbgTS9/XAaE8zzksAQer9bC4QsV9UQf7VAt/IbbdBuxl4iKbhsUWKg/zHb/2tG8vEWoVIuBiO4mAIEve46Nd2rEE9k+cQHMm7HFRp+Z6TnZ3ftfkjBSQKrYU0PrG8mmBskNoP9NpSvhqncz7QLTyfmIAUELhfCDegdc+LYQYLwPUMbepodCaZEk9QnjqZ/0cP2U4xYuoi9M9O5F6Qy2OCyNBurMyQMdMs1dj5hdGIdndGsuZFQocpjdAY7NDwATP/1wH4584Lf+EY6XmBqFBV5CSwVSA5wwgzQFJoWXmdNUjqeO+DyR2Bx7qDetndPy0tv9bSnz4oWNvXy0u+6yxHnIJgO4v9jz13yXuj+YpUr52vFROrJ7NsEOCFBbjyf54JfOo=,iv:gNuNSPxFASYyoenSxBeOZbiqDb1l3m7ZWjAyPB10HlI=,tag:rjkpRNxMtTTISeHjbzLfXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uk0y2ahfavgsgqvrtg5a22w5gytpdmjuatxtcw6kntmxhlcgreesuwzw5s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNXNzQnlPS2RrNHIvVGZq
            S0N4bXVsRWhuYnF4bENLZ2dTMGNKbTJZT3pnCkVIR3JBSkZ1MFBoaFI1S1dCbVFW
            SVJxOGZYWDdoYjd5NldCa0EvZWxTUFEKLS0tIEFWa3BScWtsckUxRk1zQVlUc3Ny
            ZTRTY1JqZWU2a0hMYlJSS1cyVFZybmMKOcjeeKtslgAMj7AXs7MoLoJGzRPdwy8q
            JT+ugWz6DB+qkIMvOgllBy+Ik0lnSxeowQEKi8OsWxK/H5m3/RWeWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hawjtl6fm5czl8cun0ve7jvsmpqpn3qlxl2lnx7ndt7682tmva2qz3drfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueTB4eVBBMmxHaW5vY2tH
            cVJwdU9IWWxLcm1scWFzVVNZTjlCbjMzMkFJCkMzOXdUaWo4ZXJ6bkFiT0VmVDUw
            Uzd3YU1ZSzdoL0RSSTZTaU9EVEJLSFkKLS0tIEh2MmRHcEJPeTg3RWtLZmM2eTdp
            SkVkSGVQQndRNkI3bWt1MmhyRmQwR00Kws0zmOF5D4ap0RivrBWZQ4i/C1LjtIWR
            MrdHYOFIa2SN18scnwKjhQlX91Pr6HJ+yUcyiz5kpiNSNgYpFOqbXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T07:55:15Z"
    mac: ENC[AES256_GCM,data:G2noNlZk5YefqijYOFZzTAkVsot8qrXireMTuj+KN7BaZM5ZT90qIaBGR795IBecqkI2Dm9I1gpfdrwIEKf+IP5j9sWEDe+txMwaISqA3gk+51KcqPCoJ6iKWogkUz04DvQsKyFR9vIWg8n/KH/3blpMxQBUCj86qw8gkYQhdRw=,iv:3tycdcrAchipUtAvP2qbxLXF9VDDZW1RKyir5iHgBzQ=,tag:dyzwQdKdykVYpBzCZKMH8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
