---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: christmas-community
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      christmas-community:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: docker.io/wingysam/christmas-community
              tag: 1.36.0
            env:
              PORT: &httpPort 8081
              SMILE: false
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: christmas-community
        ports:
          http:
            port: *httpPort

    ingress:
      app:
        className: "internal-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.bjw-s.dev
        hosts:
          - host: gifts.bjw-s.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        type: emptyDir
        advancedMounts:
          christmas-community:
            app:
              - path: /data
