---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: piped-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: piped-db-secret
    template:
      type: Opaque
      data:
        user: '{{ index . "user" }}'
        password: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-piped
