---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piped
spec:
  chart:
    spec:
      chart: piped
      version: 6.0.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: piped
  interval: 30m
  values:
    automountServiceAccountToken: false

    postgresql:
      enabled: false

    backend:
      annotations:
        configmap.reloader.stakater.com/reload: piped-backend-config
      config:
        PORT: 8080
        HTTP_WORKERS: 4
        API_URL: https://piped-api.bjw-s.dev
        PROXY_PART: "https://piped-proxy.bjw-s.dev"
        DISABLE_REGISTRATION: true
        database:
          connection_url: jdbc:postgresql://postgres-primary.database.svc.cluster.local:5432/piped
          driver_class: org.postgresql.Driver
          secret:
            name: piped-db-secret
            username: user
            password: password
      podSecurityContext:
        runAsUser: &uid 1000
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: Always
      resources:
        requests:
          cpu: 10m
          memory: 500Mi
        limits:
          memory: 2000Mi

    frontend:
      env:
        BACKEND_HOSTNAME: piped-api.bjw-s.dev
      args:
        - -c
        - |
            sed -i s/pipedapi.kavin.rocks/$BACKEND_HOSTNAME/g /usr/share/nginx/html/assets/* &&
            sed -i 's/80;/8080;/g' /etc/nginx/conf.d/default.conf &&
            /docker-entrypoint.sh nginx -g 'daemon off;'
      service:
        main:
          ports:
            http:
              port: 8080
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 256Mi

    ingress:
      main:
        ingressClassName: "internal-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.bjw-s.dev
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.bjw-s.dev, https://piped-api.bjw-s.dev, https://piped-proxy.bjw-s.dev"
        hosts:
          - host: piped.bjw-s.dev
            paths:
              - path: "/"

      backend:
        ingressClassName: "internal-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.bjw-s.dev
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.bjw-s.dev, https://piped-api.bjw-s.dev, https://piped-proxy.bjw-s.dev"
        hosts:
          - host: piped-api.bjw-s.dev
            paths:
              - path: "/"

      ytproxy:
        ingressClassName: "internal-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.bjw-s.dev
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.bjw-s.dev, https://piped-api.bjw-s.dev, https://piped-proxy.bjw-s.dev"
        hosts:
          - host: piped-proxy.bjw-s.dev
            paths:
              - path: "/"
