---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinchflat
spec:
  chart:
    spec:
      chart: app-template
      version: 3.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      pinchflat:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 44
              - 109
              - 65542 # gladius:external-services

        containers:
          app:
            image:
              repository: ghcr.io/kieraneglin/pinchflat
              tag: v2024.10.2
            env:
              PORT: &port 8945
              TZ_DATA_DIR: /tmp/elixir_tz_data
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthcheck
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 2Gi

    service:
      app:
        controller: pinchflat
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal-nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.bjw-s.dev
        hosts:
          - host: pinchflat.bjw-s.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: pinchflat-config
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: gladius.bjw-s.internal
        path: /tank/Media
        advancedMounts:
          pinchflat:
            app:
              - path: /downloads
                subPath: Library/Main/Youtube
