---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  delete-failed-pods:
    desc: Deletes pods with Failed phase
    cmds:
      - task: _delete_pods_in_phase
        vars:
          phase: Failed

  delete-succeeded-pods:
    desc: Deletes pods with Succeeded phase
    cmds:
      - task: _delete_pods_in_phase
        vars:
          phase: Succeeded

  delete-pending-pods:
    desc: Deletes pods with Pending phase
    cmds:
      - task: _delete_pods_in_phase
        vars:
          phase: Pending

  _delete_pods_in_phase:
    desc: Deletes pods with a specific phase
    internal: true
    requires:
      vars:
        - phase
    cmds:
      - for:
          var: phase
          split: ','
        cmd: kubectl delete pods --field-selector status.phase={{.ITEM}} -A --ignore-not-found=true

  sync-externalsecret:
    desc: Sync ExternalSecret resource
    summary: |
      Args:
        ns: Namespace the PVC is in (default: default)
        name: ExternalSecret to sync (default: all secrets)
    silent: true
    vars:
      ns: '{{.ns | default "default"}}'
      name: '{{ .name | default "" }}'
    cmds:
      - |
        {{if eq .name ""}}
        kubectl get externalsecret.external-secrets.io --all-namespaces --no-headers -A | awk '{print $1, $2}' \
          | xargs --max-procs=2 -l bash -c 'kubectl --namespace $0 annotate externalsecret.external-secrets.io $1 force-sync=$(date +%s) --overwrite'
        {{else}}
        kubectl --namespace {{.ns}} annotate externalsecret.external-secrets.io {{.name}} force-sync=$(date +%s) --overwrite
        {{end}}
    preconditions:
      - sh: '{{if ne .name ""}}kubectl --namespace {{.ns}} get externalsecret {{.name}}{{end}}'
        msg: "ExternalSecret {{.name}} not found in namespace {{.ns}}"
