---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Docs: Release to GitHub pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-publish.yaml
      - docs/**

jobs:
  release-docs:
    name: Release documentation
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Build docs
        uses: docker://ghcr.io/bjw-s-labs/mdbook:0.4.42@sha256:70d5f4ae637b598135473f7fc92f3ee2046dd1d821e4251629b17e880571a208
        with:
          args: bash -c "cd docs && mdbook build"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          publish_dir: ./docs/book/html
